version: '3.1'

services:
  nginx:
      image: nginx:alpine
      ports:
          - ${WEB_EXPOSE_PORT:-8080}:${WEB_PORT:-80}
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro   
  fpm:
      build: 
        context: .
        dockerfile: fpm.dockerfile
      volumes:
          - ./lara/laravel:/usr/src/myapp
      expose:
          - ${FPM_PORT:-9000}
  db:
    image: percona
    restart: always
    volumes:
      - db-volume:/var/lib/backup/data
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-example}
      MYSQL_DATABASE: ${DB_DATABASE:-orphandb}
      MYSQL_USER: ${DB_USERNAME:-test}
      MYSQL_PASSWORD: ${DB_PASSWORD:-juand}
    ports:
      - ${DB_EXPOSE_PORT:-33066}:${DB_PORT:-3306}
  react:
    container_name: ${APP_NAME:-react-app}
    build:
      context: .
      dockerfile: react.dockerfile
      args: 
        APP_NAME: ./react/${APP_NAME}
    volumes:
      - ./react/${APP_NAME}:/usr/src/app
    ports:
      - ${NODE_EXPOSE_PORT:-3000}:${NODE_PORT:-3000}
    environment:
      - NODE_ENV=development 
    depends_on:
      - fpm     
volumes:
  db-volume:
